#!/bin/bash -l
set -euo pipefail

# Put our custom Jupyter Server config into appropriate platform
# This path is determined by looking at output of `jupyter --path` in the hub
# We copy both to notebook server config and jupyter server config, because either can be
# used in the JupyterHub.
cp custom_jupyter_server_config.json ${NB_PYTHON_PREFIX}/etc/jupyter/jupyter_server_config.d/
cp custom_jupyter_server_config.json ${NB_PYTHON_PREFIX}/etc/jupyter/jupyter_notebook_config.d/

# Install SpectralUnmixing Julia package
wget https://github.com/emit-sds/SpectralUnmixing/archive/refs/tags/v0.2.3.zip -P /home/jovyan/
unzip /home/jovyan/v0.2.3.zip -d /home/jovyan/
cd home/jovyan/SpectralUnmixing-0.2.3/ && julia -e 'using Pkg; Pkg.activate("."); Pkg.precompile()'
rm /home/jovyan/v0.2.3.zip
